# Generated by Django 4.0.5 on 2022-06-10 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVefification',
            new_name='EmailVerification',
        ),
    ]
